### PR TITLE
Add ilclient as external library for RPI < 4 devices

### PR DESCRIPTION
**Pull request by bespsm**
- Makefile: add ilclient as external lib for RPI<4
- textureStreamOMX: remove ilclient code

tested on RPI 3B+ using command:
`glslViewer examples/2D/00_tests/test.frag /opt/vc/src/hello_pi/hello_video/test.h264`

### CODE REVIEW

**Comment by bespsm** [comment]
@patriciogonzalezvivo please take a look. I'm trying to grasp source code by fixing some minor things :smile:

**Comment by patriciogonzalezvivo** [comment]
This is a fantastic clean up! how this behaves on a regular linux or macos laptop?

**Comment by bespsm** [comment]
It builds only for RPI with LEGACY driver. for the other platforms it skips (including linux and macos)

**Comment by patriciogonzalezvivo** [comment]
I test it on Ubuntu 20.04 and everything seams fine. Thanks!!!

**Comment by patriciogonzalezvivo** [comment]
Ok.... any what's the best way to solve this?

```
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_RPI -Wno-psabi  -DUSE_VCHIQ_ARM -DOMX_SKIP64BIT -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DHAVE_LIBOPENMAX=2 -DOMX -DUSE_EXTERNAL_OMX  -DGLM_FORCE_CXX14 -DDRIVER_LEGACY -DSUPPORT_FOR_LI
BAV  -Isrc/ -Iinclude/ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -g -c include/oscpack/ip/posix/NetworkingUtils.cpp -o include/oscpack/ip/p
osix/NetworkingUtils.o -Wno-deprecated-declarations
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_RPI -Wno-psabi  -DUSE_VCHIQ_ARM -DOMX_SKIP64BIT -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DHAVE_LIBOPENMAX=2 -DOMX -DUSE_EXTERNAL_OMX  -DGLM_FORCE_CXX14 -DDRIVER_LEGACY -DSUPPORT_FOR_LI
BAV  -Isrc/ -Iinclude/ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -g -c include/oscpack/ip/posix/UdpSocket.cpp -o include/oscpack/ip/posix/U
dpSocket.o -Wno-deprecated-declarations
make -C /opt/vc/src/hello_pi/libs/ilclient
make[1]: Entering directory '/opt/vc/src/hello_pi/libs/ilclient'
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vector
ize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I/opt/vc/src/hello_pi/libs
/ilclient -I/opt/vc/src/hello_pi/libs/vgfont -I/opt/vc/src/hello_pi/libs/revision -g -c ilclient.c -o ilclient.o -Wno-deprecated-declarations
Assembler messages:
Fatal error: can't create ilclient.o: Permission denied
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vector
ize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I/opt/vc/src/hello_pi/libs
/ilclient -I/opt/vc/src/hello_pi/libs/vgfont -I/opt/vc/src/hello_pi/libs/revision -g -c ilcore.c -o ilcore.o -Wno-deprecated-declarations
Assembler messages:
Fatal error: can't create ilcore.o: Permission denied
../../Makefile.include:11: recipe for target 'ilcore.o' failed
make[1]: *** [ilcore.o] Error 2
make[1]: *** Waiting for unfinished jobs....
../../Makefile.include:11: recipe for target 'ilclient.o' failed
make[1]: *** [ilclient.o] Error 2
make[1]: Leaving directory '/opt/vc/src/hello_pi/libs/ilclient'
Makefile:108: recipe for target '/opt/vc/src/hello_pi/libs/ilclient/libilclient.a' failed
make: *** [/opt/vc/src/hello_pi/libs/ilclient/libilclient.a] Error 2
make: *** Waiting for unfinished jobs....

```

**Comment by bespsm** [comment]
what is the output of this command on your RPI:
`ls -l /opt/vc/src/hello_pi/libs`

**Pull request merged**
