### PR TITLE
automatically detect shadertoy.com image shaders

### PR DESCRIPTION
**Pull request by doug-moen**
Only iResolution and iGlobalTime uniforms are currently supported.

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
I belive `u_date` is very identical that `iDate` and `u_delta` is to `iTimeDelta`... same for `iMouse` to `u_mouse` ??

**Comment by brucelane** [comment]
I do it on the C++ side in my videodromm project: https://github.com/videodromm/Cinder-Videodromm/blob/master/src/VDShader.cpp#L106
I use glsleditor to live code shaders and send them via websockets to my c++ app...

**Comment by doug-moen** [comment]
I'm a newbie, I've only ever used iResolution and iGlobalTime.

We could certainly extend this to support the other shadertoy uniforms. However, I would need to learn how those other uniforms work in order to test them. That will take more time.

I don't think that iMouse == u_mouse, since iMouse is vec4, and u_mouse is vec2. So we'd at least need special support for iMouse. For the others, I don't know what's involved yet.

Oops, I just noticed that my support for iResolution is incorrect. iResolution is a vec3, while u_resolution is a vec2. The only reason this works in my tests is that my code only ever refers to the x and y components of iResolution. iResolution.z is pixel aspect ratio, usually 1.0.

**Comment by doug-moen** [comment]
If you want full and correct support for all shadertoy image shader uniforms, then the solution will no longer be "simple and altogether in one part of the code" as you originally requested. The shadertoy support will provide uniform data that is not available in standard glslViewer uniforms. So how far down this path do you want to go? My current pull request is pretty simple, and works for the most common cases.

**Comment by patriciogonzalezvivo** [comment]
for `iResolution` you can do `#define iResolution vec3(u_resolution,1.)` or better replacing the `1.` for the out put of `getPixelDensity()`

**Comment by patriciogonzalezvivo** [comment]
similarly `iMouse` could have a naive version w `#define iMouse vec4(u_mouse.x,u_mouse.y,0.,0.)`

**Comment by patriciogonzalezvivo** [comment]
`iData` I belive is the same as `u_data`
similarly to `iTimeDelta` and `u_delta` 

The `uniform sample2D` is totally different : / 
So no back compatibility there : /

**Comment by patriciogonzalezvivo** [comment]
how that sounds?

**Comment by doug-moen** [comment]
iMouse is completely different from u_mouse.

iMouse.xy = current pixel coords (if LMB is down).
iMouse.zw = click pixel

Actual shadertoys do not respond to the mouse unless the button is down, based on my tests.
For example, https://www.shadertoy.com/view/XslGRr

By contrast, u_mouse is the current pixel coords regardless of whether LMB is down or up.

It would make more sense to support both u_mouse and iMouse as separate uniforms: they are both useful, in different use cases.

**Comment by patriciogonzalezvivo** [comment]
mmm... gr... I was trying to prevent that... ok... only for `iMouse`... : /

**Comment by doug-moen** [comment]
@patriciogonzalezvivo said `#define iResolution vec3(u_resolution,1.)`

I just downloaded the implementation of shadertoy image shaders, and iResolution.z is hard coded to 1.0. So that's easy; your implementation is completely compatible.

**Comment by patriciogonzalezvivo** [comment]
This is great! thanks a lot! One question, why you call them image shaders? isn't right to call them fragment shaders?

**Comment by doug-moen** [comment]
See https://www.shadertoy.com/howto

ShaderToy supports several different shader types, with different entry
points. The entry point to an image shader is mainImage. So an image shader
is a fragment shader that conforms to the image shader api and defines a
mainImage entry point.

I'm still working on iMouse, by the way.

**Comment by patriciogonzalezvivo** [comment]
I see! makes sense! thanks! let me know when you are done with it! : )

**Comment by doug-moen** [comment]
Okay, I'm done with this change.

**Comment by patriciogonzalezvivo** [comment]
Awesome!! thanks again!

**Comment by doug-moen** [comment]
I was reading the code, and noticed that my iMouse support will not work on Raspberry Pi.
I'm not in a position to fix this since I don't have a Raspberry Pi dev setup.

**Comment by patriciogonzalezvivo** [comment]
Why?

**Comment by patriciogonzalezvivo** [comment]
I see... why did you add the iMouse variable on the CPU code... I though we were doing "#defines"

**Comment by patriciogonzalezvivo** [comment]
yeah... mmmmm.... I can do it... still...  I'm not really happy with having both` u_mouse` and `iMouse`. But I think shadertoy compatibility is an important step... will happen sooner or later... my worries are on keeping cross compatibility with the book of shaders and 'glslCanvas' and 'glslEditor'

**Comment by patriciogonzalezvivo** [comment]
I'm testing using `numbers.frag` and I'm getting this error:

screen shot 2017-02-08 at 10 58 04 am

ideas?

**Comment by patriciogonzalezvivo** [comment]
In fact I do! : ) the `void main()` wrapper calls for a `mainImage(vec4 out, vec4 in)` function when shadertoy actually use  `mainImage(vec4 out, vec2 in)`... is that consistent? what does the spec said about that? I'm also curious if this shader was compiling for you

**Comment by patriciogonzalezvivo** [comment]
fixed! https://github.com/patriciogonzalezvivo/glslViewer/commit/74fbdc07fe727e7d82d0ecdecfe3c89d87e6cab6

**Comment by doug-moen** [comment]
I tested 74fbdc0 and it works for me.
I don't know why the old code also worked for me. Apparently my driver is not fussy about type errors. I'm using a recent nVidia driver.

**Comment by patriciogonzalezvivo** [comment]
haa... yeah... Nvidia is super permissive

**Comment by patriciogonzalezvivo** [comment]
this is awesome! thanks for your contribution

screen shot 2017-02-08 at 11 24 46 am

**Comment by patriciogonzalezvivo** [comment]
@doug-moen Do you know if it's possible to download shaders from shaderToy? Thinking on adding support on `glslLoad` to automatically download shadertoy shader passing their code name

**Comment by patriciogonzalezvivo** [comment]
@brucelane what do you think on doing a similar cross implementation to `glslCanvas` ??

**Comment by doug-moen** [comment]
Well, you could use the official ShaderToy web API:
https://www.shadertoy.com/api

That would be more polite than reverse engineering their internal API.

I'm glad you like my contribution.

**Comment by patriciogonzalezvivo** [comment]
Seams not working : / 

https://www.shadertoy.com/api/v1/shaders/Ms2SD1?key=rt8tWH

**Comment by doug-moen** [comment]
Well, there is always reverse engineering. Make sure to read the
"acceptable use" policy on ShaderToy.com to make sure this is legit.

Here's some javascript that appears to load a JSON object describing a
shader:

function loadShader()
{
    try
    {
        var httpReq = new XMLHttpRequest();
        httpReq.addEventListener( 'load', function ( event )
        {
            //console.log( "R " +  event.target.readyState + "  S " +
event.target.status + " J " + event.target.response);

            var jsnShader = event.target.response;
            if( jsnShader===null ) { alert( "Error loading shader" );
return; };

            //console.log( jsnShader );

            dataLoadShader( jsnShader );
        }, false );
        httpReq.addEventListener( 'error', function () { alert( "Error
loading shader" ); }, false );

        httpReq.open( "POST", "/shadertoy", true );
        httpReq.responseType = "json";
        httpReq.setRequestHeader('Content-Type',
'application/x-www-form-urlencoded');
        //httpReq.setRequestHeader('Content-Type', 'application/json');
        //httpReq.setRequestHeader('Content-Type', 'text/plain');

        var str = "{ \"shaders\" : [\"" + gShaderID + "\"] }";
        str = "s=" + encodeURIComponent( str );
        httpReq.send( str  );
    }
    catch(e)
    {
         return;
    }
}

Maybe this fetches the same JSON object you were trying to access using the
public API?

**Pull request merged**
