### PR TITLE
Revert "Add ilclient as external library for RPI < 4 devices"

### PR DESCRIPTION
**Pull request by patriciogonzalezvivo**
Reverts patriciogonzalezvivo/glslViewer#205 
Reverting this one until we have a solution.

### CODE REVIEW

**Comment by bespsm** [comment]
what is the output of this command on your RPI @patriciogonzalezvivo :
`ls -l /opt/vc/src/hello_pi/libs`

**Comment by bespsm** [comment]
@patriciogonzalezvivo Can be that you RPI user is not in the group "users", that are allowed to write to `/opt/vc/src/hello_pi/libs` directory.
Try: `cat /etc/group | grep users`
if it's not there, just do:
`usermod -a -G users <your-user>`

**Comment by bespsm** [comment]
as alternative, I can copy `/opt/vc/src/hello_pi/libs` dir to the source code directory and add to the build. 
This way you don't need to add user to "users" group. @patriciogonzalezvivo what do you think?

**Comment by patriciogonzalezvivo** [comment]
my user is already part of users, is still failing : ( 

```
...
include/oscpack/osc/OscReceivedElements.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_RPI -Wno-psabi  -DUSE_VCHIQ_ARM -DOMX_SKIP64BIT -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DHAVE_LIBOPENMAX=2 -DOMX -DUSE_EXTERNAL_OMX  -DGLM_FORCE_CXX14 -DDRIVER_LEGACY -DSUPPORT_FOR_LIBAV  -Isrc/ -Iinclude/ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -g -c include/oscpack/osc/OscReceivedElements.cpp -o include/oscpack/osc/OscReceivedElements.o -Wno-deprecated-declarations
include/oscpack/osc/OscReceivedElements.cpp: In function ‘const char* osc::FindStr4End(const char*, const char*)’:
include/oscpack/osc/OscReceivedElements.cpp:65:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (p >= end)
     ^~
include/oscpack/osc/OscReceivedElements.cpp:68:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  if (p[0] == '\0')    // special case for SuperCollider integer address pattern
  ^~
include/oscpack/ip/posix/NetworkingUtils.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_RPI -Wno-psabi  -DUSE_VCHIQ_ARM -DOMX_SKIP64BIT -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DHAVE_LIBOPENMAX=2 -DOMX -DUSE_EXTERNAL_OMX  -DGLM_FORCE_CXX14 -DDRIVER_LEGACY -DSUPPORT_FOR_LIBAV  -Isrc/ -Iinclude/ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -g -c include/oscpack/ip/posix/NetworkingUtils.cpp -o include/oscpack/ip/posix/NetworkingUtils.o -Wno-deprecated-declarations
include/oscpack/ip/posix/UdpSocket.o
g++ -Wall -O3 -std=c++11 -fpermissive -DPLATFORM_RPI -Wno-psabi  -DUSE_VCHIQ_ARM -DOMX_SKIP64BIT -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DHAVE_LIBOPENMAX=2 -DOMX -DUSE_EXTERNAL_OMX  -DGLM_FORCE_CXX14 -DDRIVER_LEGACY -DSUPPORT_FOR_LIBAV  -Isrc/ -Iinclude/ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -g -c include/oscpack/ip/posix/UdpSocket.cpp -o include/oscpack/ip/posix/UdpSocket.o -Wno-deprecated-declarations
make -C /opt/vc/src/hello_pi/libs/ilclient
make[1]: Entering directory '/opt/vc/src/hello_pi/libs/ilclient'
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/src/hello_pi/libs/vgfont -I/opt/vc/src/hello_pi/libs/revision -g -c ilclient.c -o ilclient.o -Wno-deprecated-declarations
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/src/hello_pi/libs/vgfont -I/opt/vc/src/hello_pi/libs/revision -g -c ilcore.c -o ilcore.o -Wno-deprecated-declarations
Assembler messages:
Fatal error: can't create ilclient.o: Permission denied
Assembler messages:
Fatal error: can't create ilcore.o: Permission denied
../../Makefile.include:11: recipe for target 'ilcore.o' failed
make[1]: *** [ilcore.o] Error 2
make[1]: *** Waiting for unfinished jobs....
../../Makefile.include:11: recipe for target 'ilclient.o' failed
make[1]: *** [ilclient.o] Error 2
make[1]: Leaving directory '/opt/vc/src/hello_pi/libs/ilclient'
Makefile:108: recipe for target '/opt/vc/src/hello_pi/libs/ilclient/libilclient.a' failed
make: *** [/opt/vc/src/hello_pi/libs/ilclient/libilclient.a] Error 2
make: *** Waiting for unfinished jobs....
[~/glslViewer]$ cat /etc/group | grep users                                                                                                                                                                                                                                                                          *[master]
users:x:100:patricio
[~/glslViewer]$ ls -l /opt/vc/src/hello_pi/libs                                                                                                                                                                                                                                                                      *[master]
total 12
drwxrwxr-x 2 root users 4096 Aug 24  2020 ilclient
drwxrwxr-x 2 root users 4096 Aug 24  2020 revision
drwxrwxr-x 2 root users 4096 Aug 24  2020 vgfont
[~/glslViewer]$  
```

**Comment by patriciogonzalezvivo** [comment]
Mmmm... seams to be a problem of this host. It happens even if I try to compile it on that folder.

```
[/opt/vc/src/hello_pi]$ make
make -C libs/ilclient
make[1]: Entering directory '/opt/vc/src/hello_pi/libs/ilclient'
cc -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -Wall -g -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -ftree-vectorize -pipe -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./ -I/opt/vc/src/hello_pi/libs/ilclient -I/opt/vc/src/hello_pi/libs/vgfont -I/opt/vc/src/hello_pi/libs/revision -g -c ilclient.c -o ilclient.o -Wno-deprecated-declarations
Assembler messages:
Fatal error: can't create ilclient.o: Permission denied
../../Makefile.include:11: recipe for target 'ilclient.o' failed
make[1]: *** [ilclient.o] Error 2
make[1]: Leaving directory '/opt/vc/src/hello_pi/libs/ilclient'
Makefile:4: recipe for target 'libs/ilclient/libilclient.a' failed
make: *** [libs/ilclient/libilclient.a] Error 2
[/opt/vc/src/hello_pi]$    
```

And  I just checked and seams to be working correctly on other hosts. Sorry to bother you! I will close this PR given that is already merge.
Thanks so much for your work!

I have  been doing some research and seams the the flipping of the OMX video is possible if we use "video_render" instead of "egl_render". But then there are some complexities on how to put it on a texture

**Pull request closed without merging**
