### PR TITLE
Add support for #version directive

### PR DESCRIPTION
**Pull request by KamikaTze-K2**
These changes add support for #version directives as requested by issue #85 and solves the preprocessor error described by the issue #67.

The changes where done in src/gl/shader.cpp, in Shader::compileShader().

The current implementation only covers the typical usage of the `#version` directive at the very beginning of the fragment shader code. It will not to properly detect and handle other valid shaders using the `#version` directive after initial spaces, lines or comments (An additional issue could be opened for addressing this).

If a `#version` directive is found in `_src` then it is moved to the beginning of `prolog`, it additionally correctly handle the generation of the `#line n` directive for properly conciliating the lines in GLSL error messages and the line numbers in the user’s editor.

The code is a little bit verbose due to my habit of writing comments everywhere, and the style is possibly sub par because I'm not a C++ developer.

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Thanks you @KamikaTze-K2 !

**Comment by KamikaTze-K2** [comment]
Hola Patricio, saludos desde las Alemanias,

I would greatly appreciate to have some feedback on this (rejected?) pull request. Is not like I'm trying to force you to merge my code into your project. Bur more like I would like to understand the reason of the almost immediate and seemly automatic close operation on it. Did I missed or offended some contribution guidelines?

Original Motivation: 

The lack of #version directive support seems to be a recurring topic among people using glslViewer, and after making my first steps in GLSL I hit this issue within a few days of coding in my simple pipeline under linux (code-OSS + XFCE_terminal + glslViewer). And after looking for alternatives I ended up realizing that the simplicity of use and the flexibility of this software is almost unmatched. That was the moment I decided to make a simple fix for this issue, and here is the resulting pull request for it.

Desde ya, muchas gracias.

**Comment by patriciogonzalezvivo** [comment]
Hi! I'm really sorry! I close it with out noticing. My intention was always to merge it. Thanks again

**Comment by KamikaTze-K2** [comment]
Hola Patricio,

I can try and take a look, although I'm not proficient with Travis.

but... Looks like the docker container is failing to fetch "something" :tm: and it fails afterwards, which is quite a weak design to use docker for something that is not able to run consistently.

Give me some time to get into this.

**Comment by patriciogonzalezvivo** [comment]
Thanks! Maybe @yvan-sraka can help?

**Pull request merged**
