### PR TITLE
Asynchronously write rendered frames to disk

### PR DESCRIPTION
**Pull request by ben-hansske**
The sequence command renders a sequence of frames and writes it to disk. I noticed, that rendering is normally faster than writing the images to disk. Therefore I used multiple threads to save the previously rendered frames.

See https://github.com/patriciogonzalezvivo/glslViewer/issues/207#issue-831277825

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
This is awesome! works like a charm. On what platforms did you test it? ( I just did on ubuntu 20.04)

**Comment by ben-hansske** [comment]
So far I only tried Arch Linux with gcc 10.2.

Just a few more questions:

- Is it ok that I just copied https://github.com/rvaser/thread_pool in the subfolder src/thread_pool?
- Is it ok that both the number of threads and the maximum length of the Queue are fixed constants? Or should I try to expose these via an command line argument or something like that?

**Comment by patriciogonzalezvivo** [comment]
I was going to ask you:
 - to move `thread_pool` to [`include/`](https://github.com/patriciogonzalezvivo/glslViewer/tree/master/include)
 - fix the indentation and style to match the rest of the project

I think the constant are ok for now. If they can use a `#ifndef` will be perfect so they can change on compilation to adapt to underpower systems like raspberry pi

**Comment by ben-hansske** [comment]
Thank you for your feedback!
Do you mean by an `#ifndef` something like
```
#ifndef GLSLVIEWER_MAX_FRAMES_IN_QUEUE
#define GLSLVIEWER_MAX_FRAMES_IN_QUEUE 50
#endif
```
For the number of threads I think that the best fit would be something like
```
std::max(1, std::thread::hardware_concurrency() - 1)
```

**Comment by patriciogonzalezvivo** [comment]
mmm... that makes sense... both looks greats. I think `MAX_FRAMES_IN_QUEUE` is better than `GLSLVIEWER_MAX_FRAMES_IN_QUEUE` I'm not using `GLSLVIEWER_` any where else : S.

Thanks so much for the diligence and patience! I'm very excited for this. Do you think this will bring issues on Windws?

**Comment by ben-hansske** [comment]
It made me very happy to contribute and improve this awesome peace of software!

Regarding issues on windows: Both the thread pool implementation and my code only use common c++11 STL-features for threading. I did not have to deal with file paths or anything else that is platform specific. Therefore I couldn't think of any potential issue on windows.

My only concern would be memory consumption: Per default MAX_FRAMES_IN_QUEUE is set to 50, that means that there can be at most be 50 Images in ram. They would consume (assuming 1080p) roughly 400Mb. As long as users don't try to render huge images, this should be ok on most platforms.

**Comment by ben-hansske** [comment]
Maybe it would be better to set a constrain on the memory consumption and not directly on the number of images in the queue?

**Comment by patriciogonzalezvivo** [comment]
nice point! Very well thought. What would be an elegant way to prevent it to crash something like a headless render running on a raspberry pi. #askingforafriend : )

**Comment by ben-hansske** [comment]
Well I guess at that point it might be a good idea to accumulate the number of bytes consumed by all the frames in the queue. I read through that in order to see what possibilities there are to get the avaibable memory: https://stackoverflow.com/questions/2513505/how-to-get-available-memory-c-g
However, there is no failsafe because of heap fragmentation. I would try to go for something like this:
```
if ( consumed_memory > max_consume_memory || memory_availabla_on_system() < 200mb) {
     safe_frame_directly_to_disk()
}
else {
    put_frame_into_save_queue();
}
```

`max_consume_memory` could be some kind of command line flag to give users more control.

**Comment by patriciogonzalezvivo** [comment]
I'm a bit out of scope. As long there is a good default and some documentation on the wiki I cool following your lead. Multi thread memory management is not my strongest hat

**Comment by patriciogonzalezvivo** [comment]
Let me know when you are ready to merge : )

**Comment by patriciogonzalezvivo** [comment]
Hi @ben-hansske! just checking who you are doing with this. Hope I didn't add extra complexity. I'm happy to settle down following your lead on the matter.

**Comment by ben-hansske** [comment]
Hi! Sorry, I am currently a little busy, but I am sure that I can come up with something in roughly a week.

**Comment by patriciogonzalezvivo** [comment]
No rush! I was just double checking that you didn't felt discouraged.

**Comment by ben-hansske** [comment]
I added the command `max_mem_in_queue` which allows to control how much memory can be allocated for images in the save queue. I think this would be a good solution, since users can trade memory vs. speed on their own. How do you think about that? I set the default amount of memory to 500 MB, which should be sufficient for most cases.

**Comment by ben-hansske** [comment]
Maybe its a bit but cumbersome that max_mem_in_queue has to be specified in bytes?

**Comment by patriciogonzalezvivo** [comment]
That's a great compromise! I love it. I think if a user goes down that path he probably knows what he is doing. Do you mind adding it to the wiki?
Thanks so much again! This is a great feature that will make a huge impact on the experience.
Thanks so much!

**Comment by ben-hansske** [comment]
I will definitely add a wiki entry for that! The list of commands would be the correct place, right?
I am very happy that you like it :)

**Comment by ben-hansske** [comment]
I wiki entry, but also found out that I didn't formattet the string describing `max_mem_in_queue` correctly in `sandbox.cpp`. Therefore the output of the help command was something like that: 
```
// camera_position[,<x>,<y>,<z>]  get or set the camera position.
// camera_exposure[,<aper.>,<shutter>,<sensit.>]  get or set the camera exposure values.
// set the maximum amount of memory used by a queue to save images to disk, note: a higher amount of memory can result in better save times
```
Notice that I forget to include the name of the command itself. I will address this in a second pr.

**Comment by patriciogonzalezvivo** [comment]
Thanks for fixing it!!

**Pull request merged**
