### PR TITLE
Windows support 

### PR DESCRIPTION
**Pull request by mihaisebea**
! so far it compiles and runs 
! not sure if anything is broken
! i added glfw as a submodule 
! for glew I didnt find an official repo so i just added the code :(
! issues and pr are welcome

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
@mihaisebea  This is fantastic! I will install windows in a VM asap so I can review it and check that doesn't break the other platforms. Thanks so much!

**Comment by patriciogonzalezvivo** [comment]
I just test it on several Linux distributions and MacOS and seem to be compiling correctly.

Do you mind adding to the wiki what do I need to compile and Install in windows? I'm preparing VM for it and I barelly know what I need.

I will bug you latter about house keeping.

THANKS again!

**Comment by patriciogonzalezvivo** [comment]
@mihaisebea Do you think it will be ok to move `KHR/khrplaform.h` to the include folder? What about `StdAfx.h` and `StdAfx.cpp` ??

**Comment by mihaisebea** [comment]
@patriciogonzalezvivo I added the section from the readme.md in the wiki as well.
I'm assuming you have visual studio installed.
Related to khrplatform.h In my mind if a project is a library the include folder should have ONLY the public headers. If it's an application it should not have an include folder, all files should be in the src folder.
StdAfx.h and StdAfx.cpp are precompiled headers that greatly reduce compilation time. I can give you some numbers with and without if you are interested.

**Comment by mihaisebea** [comment]
I have the numbers. On a 8 core 9700K compiling only the glslviwer project:
*without precompiled header: 18s 
*with precompiled header: 6.7s

**Comment by patriciogonzalezvivo** [comment]
Sorry! I didn't realize the README notes. Sorry and thanks for doing it.
I'm running vs2017 and I'm getting this from `glslViewer.sln` 
Screen Shot 2019-10-22 at 7 53 23 AM

**Comment by patriciogonzalezvivo** [comment]
Ok I uninstall VS2017 and installing VS2019. Is this settings sufficient?
Screen Shot 2019-10-22 at 8 20 29 AM

**Comment by patriciogonzalezvivo** [comment]
YAY!! it worked!
Screen Shot 2019-10-22 at 8 58 09 AM

**Comment by patriciogonzalezvivo** [comment]
@mihaisebea Nice point related to `khrplatform.h` you are right. I guess I'm trying to separate first and 3rd part files. Do you suggest naming it differently could be a solution?

**Pull request merged**
